### ISSUE TITLE
More?

### ISSUE THREAD

**Issue by iotech-fvtt** [brunocalado/macro-manager#1]
Please consider supporting more than 5 Macro managers. I know the settings are already unwieldly at 5, but a tab or accordion would help with that.

I know I can put MANY macros in each Macro Manager, but I can easily come up with more than 5 categories of macros I'd like to use this for. 

Thanks!

**Comment by brunocalado** [comment]
> Please consider supporting more than 5 Macro managers. I know the settings are already unwieldly at 5, but a tab or accordion would help with that.
> 
> I know I can put MANY macros in each Macro Manager, but I can easily come up with more than 5 categories of macros I'd like to use this for.
> 
> Thanks!

I'll make it 1-9.

**Comment by brunocalado** [comment]
done
