### ISSUE TITLE
Feature Request: Subheaders in macro Manager Slots

### ISSUE THREAD

**Issue by PlasticMohawk** [brunocalado/macro-manager#3]
As a user, I want to add multiple groups of macros to MM slots, and have a subheader to separate them.

For example, I have macros for actor attribute checks/saves. I also have macros for skill checks. I would like to have them all in one group, but with an "Attributes" subheader and a "Skills" subheader.

I could use a "dummy" macro for this, but it would be great to use a keyword, such as `Macro 1; Macro 2; ##mySubheaderTitle##; Macro 3; Macro 4` so as not to clutter my macros space up with "fake" macros.

**Comment by brunocalado** [comment]
Dummy macro is the custom macro?

**Comment by PlasticMohawk** [comment]
What I meant is, `##mySubheaderTitle##` is just to represent whatever would be required to insert a subheader. RIght now it can be done with a "fake" macro where all I need is the subheader title, ideally there would be some snippet to insert to make a better-looking subheader.

I hope that explanation makes sense.

**Comment by brunocalado** [comment]
> 

I think so. I'll check out.

**Comment by brunocalado** [comment]
done

**Comment by PlasticMohawk** [comment]
Thanks for this! Is it possible to style this subheader with a different color or tint (configurable in settings)?

**Comment by PlasticMohawk** [comment]
Just saw the update, thanks! :) However, and this is my fault because I should have been more clear, I meant the background-color using a custom setting, like this :)

![image](https://user-images.githubusercontent.com/5216225/198127378-09c0f0e1-9067-4932-83d0-46e6b0dbfcf7.png)

![image](https://user-images.githubusercontent.com/5216225/198128067-09c059ea-8011-4558-b40c-c3e5846e7b48.png)

**Comment by brunocalado** [comment]
color and background color?

**Comment by PlasticMohawk** [comment]
> color and background color?

Personally I only need `background-color` but if you have both it would be good, so people can make white text on black background or something, I think

**Comment by brunocalado** [comment]
update
