### ISSUE TITLE
Cannot Use a Macro from Macro Manager

### ISSUE THREAD

**Issue by thorgibrewer** [brunocalado/macro-manager#5]
Finally able to make a list that appears in the Macro Window. For example, I made Macro Manage 2 only have Mass Roll macro listed see images 1 and 2. But when I try to use it I get the following error shown in image 3. Am I doing something wrong?

<img width="433" alt="image" src="https://user-images.githubusercontent.com/69551564/183529033-0543be01-63db-49c6-8aa8-d989ed0a06e3.png">

<img width="300" alt="image" src="https://user-images.githubusercontent.com/69551564/183528985-6280815c-efab-4584-a427-60a941e625d0.png">

<img width="389" alt="image" src="https://user-images.githubusercontent.com/69551564/183528950-a06b11e3-7d71-4476-ae85-5a5959fed492.png">

**Comment by brunocalado** [comment]
I'll fix

**Comment by brunocalado** [comment]
fixed
