### ISSUE TITLE
Error when trying to use a macro from the Macro Manager

### ISSUE THREAD

**Issue by bearsy1** [brunocalado/macro-manager#6]
Liking the idea of it, I installed your module and gave it a try. Getting things set up was a cake-walk, but when I go to click and activate a given macro from the macro manager, I get the following as an error in the console (but otherwise nothing happens in foundry). Is it a conflict with maybe lib-wrapper or the other module maximize reopened sheets? 

If I click the macro in the hotbar or press the corresponding number key, the macros run fine.

> Uncaught (in promise) TypeError: can't assign to property "default" on 3: not an object
[Detected 3 packages: macro-manager, lib-wrapper, qol-maximize-reopened-sheets]
    macroRun api.js:256
    callback api.js:82
    submit foundry.js:55744
    _onClickButton foundry.js:55673
    jQuery 9
    activateListeners foundry.js:55645
    _render foundry.js:5044
    render foundry.js:4973
    call_wrapped libWrapper-wrapper.js:507
    applicationRenderWrapper qol-maximize-reopened-sheets.js:96
    call_wrapper libWrapper-wrapper.js:616
    render#0 libWrapper-wrapper.js:189
    openCustomMacroManager api.js:90
    openMacroManager api.js:19
    onDown init.js:659
    _executeKeybind foundry.js:2111
    _processKeyboardContext foundry.js:2150
    _handleKeyboardEvent foundry.js:2188
    KeyboardManager foundry.js:1837
api.js:256:5

Foundry 10.285
DnD5e 2.0.3
Forge Hosted
Macro Manager 0.2.2
Lib-wrapper 1.12.10.0
QoL Maximize Reopened Sheets 1.0.4

**Comment by brunocalado** [comment]
Working on it.

**Comment by brunocalado** [comment]
fixed, update
